defmodule Project3Web.Router do
  alias Project3Web.Page3_PubSubs
  use Project3Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {Project3Web.Layouts, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Project3Web do
    pipe_through :browser
    live "/", LivePageTwoPeriodicalUpdates
    live "/one", LivePageOne_ButtonsStylesForms
    live "/3a", PubSubPage.PubSub_Send
    live "/3b", PubSubPage.PubSub_Receive
    live "/3all1", PubSubPage.PubSub_AllIn1
    live "/3all2", PubSubPage.PubSub_AllIn2
    get "/archive", PageController, :home

    # generated by: mix phx.gen.live Accounts User users name:string age:integer
    live "/users", UserLive.Index, :index
    live "/users/new", UserLive.Index, :new
    live "/users/:id/edit", UserLive.Index, :edit

    live "/users/:id", UserLive.Show, :show
    live "/users/:id/show/edit", UserLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", Project3Web do
  #   pipe_through :api
  # end

  # Enable LiveDashboard and Swoosh mailbox preview in development
  if Application.compile_env(:project3, :dev_routes) do
    # If you want to use the LiveDashboard in production, you should put
    # it behind authentication and allow only admins to access it.
    # If your application does not have an admins-only section yet,
    # you can use Plug.BasicAuth to set up some basic authentication
    # as long as you are also using SSL (which you should anyway).
    import Phoenix.LiveDashboard.Router

    scope "/dev" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: Project3Web.Telemetry
      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end
